//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRUE_CONCEPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDuAn
    {
        public int MaDuAn { get; set; }
        public int MaSP { get; set; }
        public Nullable<double> SoLuong { get; set; }
    
        public virtual ThueDuAn ThueDuAn { get; set; }
        public virtual Product Product { get; set; }
    }
}
