//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRUE_CONCEPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int MaPhieuNhap { get; set; }
        public int IDProduct { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
    
        public virtual BaoCaoNhap BaoCaoNhap { get; set; }
        public virtual Product Product { get; set; }
    }
}
