//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRUE_CONCEPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE
    {
        public int ID { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public string Img_Url { get; set; }
    

        public IMAGE(int IDP,string pathImg)
        {
            this.IdProduct = IDP;
                this.Img_Url = pathImg;
        }
        public virtual Product Product { get; set; }
    }
}
