//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRUE_CONCEPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThueDuAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThueDuAn()
        {
            this.ChiTietDuAns = new HashSet<ChiTietDuAn>();
        }
    
        public int MaDuAn { get; set; }
        public Nullable<int> IDCustomer { get; set; }
        public string AddressCustomer { get; set; }
        public string nameCustomer { get; set; }
        public Nullable<System.DateTime> NgayThueDuAn { get; set; }
        public Nullable<System.DateTime> NgayDuKienHoanThanh { get; set; }
        public Nullable<double> NganSachDuKien { get; set; }
        public string YeuCauThietKe { get; set; }
        public string KieuThietKe { get; set; }
        public string MoTaThem { get; set; }
        public Nullable<double> PhiPhatSinh { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDuAn> ChiTietDuAns { get; set; }
        public virtual User User { get; set; }
    }
}
