//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRUE_CONCEPT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TRUE_CONCEPTEntities : DbContext
    {
        public TRUE_CONCEPTEntities()
            : base("name=TRUE_CONCEPTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<BaoCaoNhap> BaoCaoNhaps { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChiTietDuAn> ChiTietDuAns { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DbSet<ItemCart> ItemCarts { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ThueDuAn> ThueDuAns { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int usp_CancelInvoice(Nullable<int> iDOrder, Nullable<int> iDUser)
        {
            var iDOrderParameter = iDOrder.HasValue ?
                new ObjectParameter("IDOrder", iDOrder) :
                new ObjectParameter("IDOrder", typeof(int));
    
            var iDUserParameter = iDUser.HasValue ?
                new ObjectParameter("IDUser", iDUser) :
                new ObjectParameter("IDUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CancelInvoice", iDOrderParameter, iDUserParameter);
        }
    }
}
